# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/python
merge:
  script: |
    pip3 install -r requirements.txt
    /home/r/.local/bin/pytest --cov-fail-under=0
