# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: lint-py-files
on: [ "push", "pull_request" ]
jobs:
  pep8:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: 'Run PEP8'
        uses: quentinguidee/pep8-action@v1
        with:
          arguments: '--max-line-length=120'
  wemake-python-styleguide:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python 3.12
        uses: actions/setup-python@v7
        with:
          python-version: "3.14.7"
      - name: Install wemake-python-styleguide
        # renovate: datasource=pypi depName=wemake-python-styleguide
        # renovate: datasource=pypi depName=ruff
        # renovate: datasource=pypi depName=flake8-simple-var
        run: pip install wemake-python-styleguide==1.7.1 ruff==0.16.3 flake8-simple-var==0.1.0
      - name: Run ruff and wemake-python-styleguide
        run: ruff check compile.py && flake8 compile.py
